ALTER TABLE `role`
	CHANGE COLUMN `ROLE_ABLE` `ROLE_ABLE` TINYINT(1) NOT NULL DEFAULT 0 AFTER `ROLE_POPIS`;
ALTER TABLE `role`
	ADD COLUMN `NormalizedName` VARCHAR(255) NULL AFTER `ROLE_POPIS`,
	ADD COLUMN `ConcurrencyStamp` LONGTEXT NULL AFTER `NormalizedName`;
ALTER TABLE `users_8`
	CHANGE COLUMN `USER_JMENO` `USER_JMENO` VARCHAR(256) NULL DEFAULT NULL COLLATE 'utf8_czech_ci' AFTER `USER_TITUL`,
	CHANGE COLUMN `USER_HESLO` `USER_HESLO` LONGTEXT NULL DEFAULT NULL COLLATE 'cp1250_czech_cs' AFTER `USER_NICK`,
	CHANGE COLUMN `gdprNews` `gdprNews` TINYINT(1) UNSIGNED NULL DEFAULT NULL AFTER `gdprDate`,
	CHANGE COLUMN `USER_ID` `USER_ID` INT(11) NOT NULL AUTO_INCREMENT FIRST,
	CHANGE COLUMN `USER_NAZEV` `USER_NAZEV` VARCHAR(256) NULL DEFAULT NULL COLLATE 'utf8_czech_ci' AFTER `USER_PARENT`,
	CHANGE COLUMN `USER_TITUL` `USER_TITUL` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_czech_ci' AFTER `USER_NAZEV`,
	CHANGE COLUMN `USER_NICK` `USER_NICK` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8_bin' AFTER `USER_NAZEV_FIRMY`,
	CHANGE COLUMN `USER_PLATNOST` `USER_PLATNOST` TINYINT(1) NOT NULL DEFAULT 0 AFTER `USER_POSTA`,
	ADD COLUMN `NormalizedUserName` VARCHAR(255) NULL DEFAULT NULL  COLLATE 'utf8_bin' AFTER `USER_POPIS`,
	ADD COLUMN `NormalizedEmail` VARCHAR(255) NULL DEFAULT NULL AFTER `NormalizedUserName`,
	ADD COLUMN `EmailConfirmed` TINYINT(1) NOT NULL DEFAULT '0' AFTER `NormalizedEmail`,
	ADD COLUMN `SecurityStamp` LONGTEXT NULL DEFAULT NULL AFTER `EmailConfirmed`,
	ADD COLUMN `ConcurrencyStamp` LONGTEXT NULL DEFAULT NULL AFTER `SecurityStamp`,
	ADD COLUMN `PhoneNumberConfirmed` TINYINT(1) NOT NULL DEFAULT '0' AFTER `ConcurrencyStamp`,
	ADD COLUMN `TwoFactorEnabled` TINYINT(1) NOT NULL DEFAULT '0' AFTER `PhoneNumberConfirmed`,
	ADD COLUMN `LockoutEnd` DATETIME(6) NULL DEFAULT NULL AFTER `TwoFactorEnabled`,
	ADD COLUMN `LockoutEnabled` TINYINT(1) NOT NULL DEFAULT 0 AFTER `LockoutEnd`,
	ADD COLUMN `AccessFailedCount` INT NOT NULL DEFAULT '0' AFTER `LockoutEnabled`,
	CHANGE COLUMN `gdprBase` `gdprBase` TINYINT(1) UNSIGNED NULL DEFAULT NULL AFTER `AccessFailedCount`;

ALTER TABLE `users_8`
	CHANGE COLUMN `USER_NAZEV` `USER_NAZEV` VARCHAR(256) NULL DEFAULT NULL COLLATE 'utf8_czech_ci' AFTER `USER_PARENT`;
ALTER TABLE `users_8`
	CHANGE COLUMN `USER_NICK` `USER_NICK` VARCHAR(256) NULL DEFAULT NULL COLLATE 'utf8_bin' AFTER `USER_NAZEV_FIRMY`;
ALTER TABLE `users_8`
	CHANGE COLUMN `USER_PLATNOST` `USER_PLATNOST` TINYINT(1) NOT NULL DEFAULT 0 AFTER `USER_POSTA`;

ALTER TABLE `role`
	CHANGE COLUMN `ROLE_ID` `ROLE_ID` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `users_8`
	CHANGE COLUMN `USER_ID` `USER_ID` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `users_8`
	CHANGE COLUMN `USER_NUMBER` `USER_NUMBER` INT NOT NULL DEFAULT '0' AFTER `USER_DELETED`;






