ALTER TABLE `spinuser`
	DROP PRIMARY KEY;
	


ALTER TABLE `spinuser`
	ADD COLUMN `Id` INT(11) NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (`Id`);

ALTER TABLE `spinuser`
	ADD COLUMN `datum` DATETIME NOT NULL DEFAULT CURRENT_TIME()  AFTER `unix`;

