// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diva2_8.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Diva2.Core.Main.Calendar.CalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("DrahaId")
                        .HasColumnType("int");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("cal_event", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Calendar.CalIniMinute", b =>
                {
                    b.Property<int>("PobockaId")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PobockaId", "Minute");

                    b.ToTable("cal_ini_minutes", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Comunications.SmsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cislo")
                        .HasColumnType("longtext")
                        .HasColumnName("cislo");

                    b.Property<int>("CreateUnix")
                        .HasColumnType("int")
                        .HasColumnName("createUnix");

                    b.Property<double>("Credit")
                        .HasColumnType("double");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Exception")
                        .HasColumnType("longtext");

                    b.Property<string>("Kod")
                        .HasColumnType("longtext");

                    b.Property<int>("LekceId")
                        .HasColumnType("int")
                        .HasColumnName("spinID");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("pobockaID");

                    b.Property<string>("Result")
                        .HasColumnType("longtext");

                    b.Property<int>("SendUnix")
                        .HasColumnType("int")
                        .HasColumnName("sendUnix");

                    b.Property<int>("SendUserId")
                        .HasColumnType("int")
                        .HasColumnName("sendUserID");

                    b.Property<int>("Stav")
                        .HasColumnType("int")
                        .HasColumnName("sendStav");

                    b.Property<string>("Text")
                        .HasColumnType("longtext")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<bool>("Vyrizeno")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("vyrizeno");

                    b.Property<int>("ZakaznikId")
                        .HasColumnType("int")
                        .HasColumnName("zakaznikID");

                    b.HasKey("Id");

                    b.ToTable("sms", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Content.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("Controller")
                        .HasColumnType("longtext");

                    b.Property<string>("Method")
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UrlName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Lektori.Lektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Jmeno")
                        .HasColumnType("longtext")
                        .HasColumnName("jmeno");

                    b.Property<int>("Koeficient")
                        .HasColumnType("int")
                        .HasColumnName("koeficient");

                    b.Property<int>("Kredity")
                        .HasColumnType("int")
                        .HasColumnName("kredity");

                    b.Property<string>("Nick")
                        .HasColumnType("longtext")
                        .HasColumnName("nick");

                    b.Property<bool>("Platnost")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("platnost");

                    b.Property<string>("Popis")
                        .HasColumnType("longtext")
                        .HasColumnName("popis");

                    b.Property<int>("Poradi")
                        .HasColumnType("int")
                        .HasColumnName("poradi");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext")
                        .HasColumnName("tel");

                    b.Property<string>("Titul")
                        .HasColumnType("longtext")
                        .HasColumnName("titul");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<bool>("Viditelnost")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("viditelnost");

                    b.HasKey("Id");

                    b.ToTable("spinlektori", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Lektori.Mzda", b =>
                {
                    b.Property<int>("PokladnaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pokladnaID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PokladnaId"));

                    b.Property<int>("Den")
                        .HasColumnType("int")
                        .HasColumnName("den");

                    b.Property<int>("Hodina")
                        .HasColumnType("int")
                        .HasColumnName("hodina");

                    b.Property<int>("Mesic")
                        .HasColumnType("int")
                        .HasColumnName("mesic");

                    b.Property<int>("Pro100")
                        .HasColumnType("int")
                        .HasColumnName("pro100");

                    b.Property<int>("Zak01")
                        .HasColumnType("int")
                        .HasColumnName("zak01");

                    b.Property<int>("Zak02")
                        .HasColumnType("int")
                        .HasColumnName("zak02");

                    b.Property<int>("Zak03")
                        .HasColumnType("int")
                        .HasColumnName("zak03");

                    b.Property<int>("Zak04")
                        .HasColumnType("int")
                        .HasColumnName("zak04");

                    b.Property<int>("Zak05")
                        .HasColumnType("int")
                        .HasColumnName("zak05");

                    b.Property<int>("Zak06")
                        .HasColumnType("int")
                        .HasColumnName("zak06");

                    b.Property<int>("Zak07")
                        .HasColumnType("int")
                        .HasColumnName("zak07");

                    b.Property<int>("Zak08")
                        .HasColumnType("int")
                        .HasColumnName("zak08");

                    b.Property<int>("Zak09")
                        .HasColumnType("int")
                        .HasColumnName("zak09");

                    b.Property<int>("Zak10")
                        .HasColumnType("int")
                        .HasColumnName("zak10");

                    b.Property<int>("Zak11")
                        .HasColumnType("int")
                        .HasColumnName("zak11");

                    b.Property<int>("Zak12")
                        .HasColumnType("int")
                        .HasColumnName("zak12");

                    b.Property<int>("Zak13")
                        .HasColumnType("int")
                        .HasColumnName("zak13");

                    b.Property<int>("Zak14")
                        .HasColumnType("int")
                        .HasColumnName("zak14");

                    b.Property<int>("Zak15")
                        .HasColumnType("int")
                        .HasColumnName("zak15");

                    b.Property<int>("Zak16")
                        .HasColumnType("int")
                        .HasColumnName("zak16");

                    b.Property<int>("Zak17")
                        .HasColumnType("int")
                        .HasColumnName("zak17");

                    b.Property<int>("Zak18")
                        .HasColumnType("int")
                        .HasColumnName("zak18");

                    b.Property<int>("Zak19")
                        .HasColumnType("int")
                        .HasColumnName("zak19");

                    b.Property<int>("Zak20")
                        .HasColumnType("int")
                        .HasColumnName("zak20");

                    b.Property<int>("Zakaznik")
                        .HasColumnType("int")
                        .HasColumnName("zakaznik");

                    b.HasKey("PokladnaId");

                    b.ToTable("spin_mzdy", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Lessons.Lekce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Cas")
                        .HasColumnType("time(6)")
                        .HasColumnName("hodinaZacatek");

                    b.Property<bool>("CelyDen")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datum");

                    b.Property<int>("Den")
                        .HasColumnType("int")
                        .HasColumnName("denVTydnu");

                    b.Property<int?>("HodinaPoradi")
                        .HasColumnType("int")
                        .HasColumnName("hodina");

                    b.Property<int>("Kredit")
                        .HasColumnType("int")
                        .HasColumnName("kredit");

                    b.Property<int>("Lektor1")
                        .HasColumnType("int")
                        .HasColumnName("lektor");

                    b.Property<int>("Lektor2")
                        .HasColumnType("int")
                        .HasColumnName("lektor2");

                    b.Property<int>("MinutaKey")
                        .HasColumnType("int")
                        .HasColumnName("minuta");

                    b.Property<int>("Minuty")
                        .HasColumnType("int")
                        .HasColumnName("minuty");

                    b.Property<int>("MustrId")
                        .HasColumnType("int")
                        .HasColumnName("spinTID");

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext")
                        .HasColumnName("nazev");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("pobocka");

                    b.Property<int>("PocetJednotek")
                        .HasColumnType("int")
                        .HasColumnName("pocetJednotek");

                    b.Property<int>("PocetMist")
                        .HasColumnType("int")
                        .HasColumnName("pocetM");

                    b.Property<int>("PocetNahradniku")
                        .HasColumnType("int")
                        .HasColumnName("pocNahr");

                    b.Property<int>("PocetZakazniku")
                        .HasColumnType("int")
                        .HasColumnName("pocetZ");

                    b.Property<int>("Rok")
                        .HasColumnType("int")
                        .HasColumnName("rok");

                    b.Property<int>("Tyden")
                        .HasColumnType("int")
                        .HasColumnName("tyden");

                    b.Property<int>("TypHodiny")
                        .HasColumnType("int")
                        .HasColumnName("typ");

                    b.Property<int>("Verze")
                        .HasColumnType("int")
                        .HasColumnName("verze");

                    b.Property<int?>("ZauctovalUserId")
                        .HasColumnType("int")
                        .HasColumnName("zauctovalId");

                    b.Property<string>("ZauctovalUserName")
                        .HasColumnType("longtext")
                        .HasColumnName("zauctovalJmeno");

                    b.Property<bool>("Zauctovano")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("zauctovano");

                    b.Property<DateTime?>("ZauctovanoDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("zauctovalDt");

                    b.Property<int>("Zdroj")
                        .HasColumnType("int")
                        .HasColumnName("zdroj");

                    b.HasKey("Id");

                    b.ToTable("spinhod", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Lessons.LekceMustr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivni")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aktivni");

                    b.Property<string>("Cas")
                        .HasColumnType("longtext")
                        .HasColumnName("hodinaZacatek");

                    b.Property<int>("Den")
                        .HasColumnType("int")
                        .HasColumnName("denVTydnu");

                    b.Property<int>("Hodina")
                        .HasColumnType("int")
                        .HasColumnName("hodina");

                    b.Property<int>("Kredit")
                        .HasColumnType("int")
                        .HasColumnName("kredit");

                    b.Property<int>("Lektor")
                        .HasColumnType("int")
                        .HasColumnName("lektor");

                    b.Property<int>("Lektor2")
                        .HasColumnType("int")
                        .HasColumnName("lektor2");

                    b.Property<int>("MinutaKey")
                        .HasColumnType("int")
                        .HasColumnName("minuta");

                    b.Property<int>("Minuty")
                        .HasColumnType("int")
                        .HasColumnName("minuty");

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext")
                        .HasColumnName("nazev");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("pobocka");

                    b.Property<int>("PocetMist")
                        .HasColumnType("int")
                        .HasColumnName("pocetM");

                    b.Property<int>("PocetNahradniku")
                        .HasColumnType("int")
                        .HasColumnName("pocetNahr");

                    b.Property<int>("Typ")
                        .HasColumnType("int")
                        .HasColumnName("typ");

                    b.Property<int>("Zdroj")
                        .HasColumnType("int")
                        .HasColumnName("zdroj");

                    b.HasKey("Id");

                    b.ToTable("spinhod_sablona", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Lessons.LekceMustrTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivni")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aktivni");

                    b.Property<int>("Kredit")
                        .HasColumnType("int")
                        .HasColumnName("kredit");

                    b.Property<int>("Lektor")
                        .HasColumnType("int")
                        .HasColumnName("lektor");

                    b.Property<int>("Lektor2")
                        .HasColumnType("int")
                        .HasColumnName("lektor2");

                    b.Property<int>("Minuty")
                        .HasColumnType("int")
                        .HasColumnName("minuty");

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext")
                        .HasColumnName("nazev");

                    b.Property<string>("NazevTyp")
                        .HasColumnType("longtext");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int");

                    b.Property<int>("PocetMist")
                        .HasColumnType("int")
                        .HasColumnName("pocetM");

                    b.Property<int>("PocetNahradniku")
                        .HasColumnType("int")
                        .HasColumnName("pocetNahr");

                    b.Property<int>("Typ")
                        .HasColumnType("int")
                        .HasColumnName("typ");

                    b.HasKey("Id");

                    b.ToTable("spinhod_sablona_typ", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Lessons.LekceText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("spin_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("spinhod_text", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Lessons.LekceTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JednotkaMinut")
                        .HasColumnType("int")
                        .HasColumnName("jednMinut");

                    b.Property<int>("JednotkaPocet")
                        .HasColumnType("int")
                        .HasColumnName("jednPocet");

                    b.Property<int>("JednotkaPocetDo")
                        .HasColumnType("int")
                        .HasColumnName("jednPocetDo");

                    b.Property<int>("Kredit")
                        .HasColumnType("int")
                        .HasColumnName("kredit");

                    b.Property<int>("Mista")
                        .HasColumnType("int")
                        .HasColumnName("mista");

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext")
                        .HasColumnName("nazev");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("pobockaID");

                    b.Property<string>("Popis")
                        .HasColumnType("longtext")
                        .HasColumnName("popis");

                    b.Property<string>("Zkratka")
                        .HasColumnType("longtext")
                        .HasColumnName("zkratka");

                    b.HasKey("Id");

                    b.ToTable("spinhod_typ", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Lessons.LekceVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("spin_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<string>("TextUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("spinhod_video", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Main.Log8", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("logs8", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Main.MainIniCover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccount")
                        .HasColumnType("longtext")
                        .HasColumnName("BankAccount");

                    b.Property<bool>("BankAccountUse")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("Values");

                    b.Property<string>("GatePays")
                        .HasColumnType("longtext")
                        .HasColumnName("GatePays");

                    b.Property<string>("Styly")
                        .HasColumnType("longtext")
                        .HasColumnName("Styles");

                    b.Property<bool>("UseVideo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("spin_ini_main", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Notifications.NotificationDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("UserNotificationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserDeviceId");

                    b.HasIndex("SentAt", "Attempts");

                    b.HasIndex("UserNotificationId", "UserDeviceId")
                        .IsUnique();

                    b.ToTable("spin_user_notification_delivery", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Notifications.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PushToken")
                        .IsUnique();

                    b.HasIndex("UserId", "Active");

                    b.ToTable("spin_user_device", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Notifications.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReactedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SentAt", "Attempts");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("LessonId", "UserId", "Type")
                        .IsUnique();

                    b.ToTable("spin_user_notification", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.PayGates.PaysItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AddedCredit")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Hash")
                        .HasColumnType("longtext");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .HasColumnType("longtext");

                    b.Property<int>("Merchant")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentOrderId")
                        .HasColumnType("int");

                    b.Property<int>("PokladnaId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Shop")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusDesc")
                        .HasColumnType("longtext");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("pays_items", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Platby.PlatbaCas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("autorID");

                    b.Property<int>("Castka")
                        .HasColumnType("int")
                        .HasColumnName("platba");

                    b.Property<int>("Kategorie")
                        .HasColumnType("int")
                        .HasColumnName("kategorie");

                    b.Property<bool>("Platnost")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("platnost");

                    b.Property<string>("Popis")
                        .HasColumnType("longtext")
                        .HasColumnName("popis");

                    b.Property<int>("Poradi")
                        .HasColumnType("int");

                    b.Property<int>("Unix")
                        .HasColumnType("int")
                        .HasColumnName("unix");

                    b.Property<string>("Verze")
                        .HasColumnType("longtext")
                        .HasColumnName("verze");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("spin_platba_cas", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Platby.PlatbaCasPobocka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlatbaId")
                        .HasColumnType("int")
                        .HasColumnName("platbaID");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("pokladnaID");

                    b.HasKey("Id");

                    b.ToTable("spin_platba_cas_pob", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Platby.PlatbaKredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorID")
                        .HasColumnType("int")
                        .HasColumnName("autorID");

                    b.Property<int>("Castka")
                        .HasColumnType("int")
                        .HasColumnName("platba");

                    b.Property<int>("Kategorie")
                        .HasColumnType("int")
                        .HasColumnName("kategorie");

                    b.Property<int>("Kredity")
                        .HasColumnType("int")
                        .HasColumnName("kredity");

                    b.Property<bool>("Platnost")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("platnost");

                    b.Property<int>("PokladnaId")
                        .HasColumnType("int")
                        .HasColumnName("pokladnaID");

                    b.Property<string>("Popis")
                        .HasColumnType("longtext")
                        .HasColumnName("popis");

                    b.Property<int>("Poradi")
                        .HasColumnType("int");

                    b.Property<int>("Unix")
                        .HasColumnType("int")
                        .HasColumnName("unix");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("spin_platba_kredit", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Platby.PlatbaKreditCas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorID")
                        .HasColumnType("int")
                        .HasColumnName("autorID");

                    b.Property<int>("Castka")
                        .HasColumnType("int")
                        .HasColumnName("platba");

                    b.Property<int>("Kategorie")
                        .HasColumnType("int")
                        .HasColumnName("kategorie");

                    b.Property<int>("Kredity")
                        .HasColumnType("int")
                        .HasColumnName("kredity");

                    b.Property<bool>("Platnost")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("platnost");

                    b.Property<int>("PocetLidi")
                        .HasColumnType("int")
                        .HasColumnName("pocetLidi");

                    b.Property<int>("PocetMesicu")
                        .HasColumnType("int")
                        .HasColumnName("verze");

                    b.Property<int>("PokladnaId")
                        .HasColumnType("int")
                        .HasColumnName("pokladnaID");

                    b.Property<string>("Popis")
                        .HasColumnType("longtext")
                        .HasColumnName("popis");

                    b.Property<int>("Poradi")
                        .HasColumnType("int");

                    b.Property<int>("Ts")
                        .HasColumnType("int")
                        .HasColumnName("unix");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("spin_platba_kredit_cas", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Platby.Pokladna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("spin_pokladna", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Platby.PrijmoveDoklady", b =>
                {
                    b.Property<ushort>("Rok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("rok");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Rok"));

                    b.Property<int>("Hodnota")
                        .HasColumnType("int")
                        .HasColumnName("poradi");

                    b.HasKey("Rok");

                    b.ToTable("prijmove_doklady", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Pobocka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalendarSetting")
                        .HasColumnType("longtext");

                    b.Property<string>("Color1")
                        .HasColumnType("longtext")
                        .HasColumnName("color1");

                    b.Property<string>("Color2")
                        .HasColumnType("longtext")
                        .HasColumnName("color2");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Popis");

                    b.Property<int>("Kredity")
                        .HasColumnType("int")
                        .HasColumnName("kredit");

                    b.Property<int>("Minuty")
                        .HasColumnType("int")
                        .HasColumnName("minuty");

                    b.Property<string>("MotivHlavni")
                        .HasColumnType("longtext")
                        .HasColumnName("motivHlavni");

                    b.Property<string>("MotivKontra")
                        .HasColumnType("longtext")
                        .HasColumnName("motivKontra");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("Nazev");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("poradi");

                    b.Property<bool>("PobockaType")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PocetMist")
                        .HasColumnType("int")
                        .HasColumnName("pocetM");

                    b.Property<bool>("PodbarvovatObsazene")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PokladnaId")
                        .HasColumnType("int")
                        .HasColumnName("pokladnaId");

                    b.Property<int>("Typ")
                        .HasColumnType("int")
                        .HasColumnName("pobockaType");

                    b.Property<ulong>("Visible")
                        .HasColumnType("bit")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("spin_pobocka", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Pobocky.CasZacatek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Minuta")
                        .HasColumnType("int");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("Pobocka");

                    b.Property<int>("Poradi")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("timespan")
                        .HasColumnName("Zacatek");

                    b.HasKey("Id");

                    b.ToTable("spin_ini_zacatek", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Pobocky.PobockaIni", b =>
                {
                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("PobockaID");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Nazev");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("Hodnota");

                    b.HasKey("PobockaId", "Name");

                    b.ToTable("spin_ini", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.LekceUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivni")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aktivni");

                    b.Property<bool>("BylTam")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bylTam");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datum");

                    b.Property<bool>("DoMzdy")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("doMzdy");

                    b.Property<int>("KontCislo")
                        .HasColumnType("int")
                        .HasColumnName("kontCislo");

                    b.Property<int>("LekceId")
                        .HasColumnType("int")
                        .HasColumnName("spinID");

                    b.Property<bool>("Nahradnik")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("nahradnik");

                    b.Property<bool>("NahradnikJa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("nahradnikJa");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("pobockaID");

                    b.Property<int>("PokladnaId")
                        .HasColumnType("int")
                        .HasColumnName("pokladnaID");

                    b.Property<int>("Poradi")
                        .HasColumnType("int")
                        .HasColumnName("poradi");

                    b.Property<bool>("Premiera")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("premiera");

                    b.Property<int>("Unix")
                        .HasColumnType("int")
                        .HasColumnName("unix");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<int>("Zbytek")
                        .HasColumnType("int")
                        .HasColumnName("zbytek");

                    b.Property<string>("ZbytekTyp")
                        .HasColumnType("longtext")
                        .HasColumnName("zbytekTyp");

                    b.Property<int>("ZbyvaDni")
                        .HasColumnType("int")
                        .HasColumnName("zbyvaDni");

                    b.HasKey("Id");

                    b.HasIndex("LekceId");

                    b.HasIndex("UserId");

                    b.ToTable("spinuser", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserLekceChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LekceId")
                        .HasColumnType("int")
                        .HasColumnName("spinID");

                    b.Property<int>("ProvedlId")
                        .HasColumnType("int")
                        .HasColumnName("provedlID");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("spinuserchange", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserLekceLogIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FromAdministrace")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("fromAdmin");

                    b.Property<int>("KreditInit")
                        .HasColumnType("int");

                    b.Property<int>("KreditLekce")
                        .HasColumnType("int");

                    b.Property<int>("LekceId")
                        .HasColumnType("int")
                        .HasColumnName("spinID");

                    b.Property<int>("MaxPerUser")
                        .HasColumnType("int");

                    b.Property<int>("MaxPerUserTime")
                        .HasColumnType("int");

                    b.Property<int>("ObjednaneKredity")
                        .HasColumnType("int");

                    b.Property<int>("ObjednanychLekci")
                        .HasColumnType("int");

                    b.Property<int>("ObjednanychVLekci")
                        .HasColumnType("int");

                    b.Property<int>("PocetMist")
                        .HasColumnType("int");

                    b.Property<int>("PocetZakazniku")
                        .HasColumnType("int");

                    b.Property<int>("Poradi")
                        .HasColumnType("int");

                    b.Property<bool>("Pridat")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProvedlId")
                        .HasColumnType("int")
                        .HasColumnName("provedlID");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<int>("ZbytekKredit")
                        .HasColumnType("int");

                    b.Property<int>("ZbytekKreditCas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("spinuserchange_login", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserLekceLogOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ExistujeNahradnik")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("JePlatny")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LekceId")
                        .HasColumnType("int")
                        .HasColumnName("spinID");

                    b.Property<int>("PocetMist")
                        .HasColumnType("int");

                    b.Property<int>("PocetZakazniku")
                        .HasColumnType("int");

                    b.Property<int>("Poradi")
                        .HasColumnType("int");

                    b.Property<int>("ProvedlId")
                        .HasColumnType("int")
                        .HasColumnName("provedlID");

                    b.Property<bool>("SmsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SmsStatus")
                        .HasColumnType("int");

                    b.Property<int>("SmsUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("Id");

                    b.ToTable("spinuserchange_logout", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KontrolniCislo")
                        .HasColumnType("int")
                        .HasColumnName("kontrolniCislo");

                    b.Property<int>("LekceId")
                        .HasColumnType("int")
                        .HasColumnName("spinID");

                    b.Property<string>("Text")
                        .HasColumnType("longtext")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("Id");

                    b.ToTable("spinuser_text", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserTransakce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Castka")
                        .HasColumnType("int")
                        .HasColumnName("castka");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datum");

                    b.Property<int>("DoPokladny")
                        .HasColumnType("int")
                        .HasColumnName("doPokladny");

                    b.Property<int>("Doklad")
                        .HasColumnType("int")
                        .HasColumnName("doklad");

                    b.Property<int>("Increment")
                        .HasColumnType("int")
                        .HasColumnName("increment");

                    b.Property<int>("Kredit")
                        .HasColumnType("int")
                        .HasColumnName("kredit");

                    b.Property<int>("LekceId")
                        .HasColumnType("int")
                        .HasColumnName("spinID");

                    b.Property<int?>("PlatnostDoUnix")
                        .HasColumnType("int")
                        .HasColumnName("platnostDoUnix");

                    b.Property<int?>("PlatnostOdUnix")
                        .HasColumnType("int");

                    b.Property<int>("PokladnaId")
                        .HasColumnType("int")
                        .HasColumnName("pokladnaID");

                    b.Property<int>("ProvedlId")
                        .HasColumnType("int")
                        .HasColumnName("provedlID");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Typ")
                        .HasColumnType("longtext")
                        .HasColumnName("typ");

                    b.Property<int>("UnixTime")
                        .HasColumnType("int")
                        .HasColumnName("unixTime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<int?>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("videoID");

                    b.Property<bool>("ZBanky")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Zbytek")
                        .HasColumnType("int")
                        .HasColumnName("zbytek");

                    b.Property<int>("ZbyvaDni")
                        .HasColumnType("int")
                        .HasColumnName("zbyvaDni");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("spin_user_transakce", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserZbytekKredit", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<int>("PokladnaId")
                        .HasColumnType("int")
                        .HasColumnName("pokladnaID");

                    b.Property<bool>("IsSet")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("krIs");

                    b.Property<int>("Kr1")
                        .HasColumnType("int");

                    b.Property<int>("Kr1From")
                        .HasColumnType("int");

                    b.Property<int>("Kr1To")
                        .HasColumnType("int");

                    b.Property<int>("Kr2")
                        .HasColumnType("int");

                    b.Property<int>("Kr2From")
                        .HasColumnType("int");

                    b.Property<int>("Kr2To")
                        .HasColumnType("int");

                    b.Property<int>("Kredit")
                        .HasColumnType("int")
                        .HasColumnName("kredit");

                    b.Property<int>("KreditUnixTime")
                        .HasColumnType("int")
                        .HasColumnName("kreditUnixTime");

                    b.Property<int>("Rezervace")
                        .HasColumnType("int")
                        .HasColumnName("rezervace");

                    b.Property<int>("RezervaceUnixTime")
                        .HasColumnType("int")
                        .HasColumnName("rezervaceUnixTime");

                    b.HasKey("UserId", "PokladnaId");

                    b.ToTable("spin_user_zbytek_kredit", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserZbytekKreditCas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivni")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aktivni");

                    b.Property<int>("Kredit")
                        .HasColumnType("int")
                        .HasColumnName("kredit");

                    b.Property<int>("KreditUnixTime")
                        .HasColumnType("int")
                        .HasColumnName("kreditUnixTime");

                    b.Property<int>("PlatbaId")
                        .HasColumnType("int")
                        .HasColumnName("platbaID");

                    b.Property<int>("PlatnostDoUnix")
                        .HasColumnType("int")
                        .HasColumnName("platnostDoUnix");

                    b.Property<int>("PlatnostOdUnix")
                        .HasColumnType("int")
                        .HasColumnName("platnostOdUnix");

                    b.Property<int?>("PlatnostUnixBreak")
                        .HasColumnType("int")
                        .HasColumnName("platnostUnixBreak");

                    b.Property<bool>("Platny")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PocetLidi")
                        .HasColumnType("int")
                        .HasColumnName("pocetLidi");

                    b.Property<int>("PocetMesicu")
                        .HasColumnType("int")
                        .HasColumnName("pocetMesicu");

                    b.Property<int>("PokladnaId")
                        .HasColumnType("int")
                        .HasColumnName("pokladnaID");

                    b.Property<bool>("Prodlouzeno")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("spin_user_zbytek_kredit_casovy", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserZbytekKreditCasLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("PlatbaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UnixFrom")
                        .HasColumnType("int");

                    b.Property<int>("UnixTo")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("spin_user_zbytek_kredit_casovy_log", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Users.Role8", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("ROLE_POPIS");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("ROLE_NAZEV");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("PublicAble")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ROLE_ABLE");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Users.RoleRule8", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.Property<int>("PravoId")
                        .HasColumnType("int")
                        .HasColumnName("PRAVA_ID");

                    b.HasKey("RoleId", "PravoId");

                    b.ToTable("prava_for_role", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Users.Rule8", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRA_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("PRA_POPIS");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("PRA_NAZEV");

                    b.Property<bool>("PublicAble")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PRA_ABLE");

                    b.HasKey("Id");

                    b.ToTable("prava", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Users.User8", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("USER_DELETED");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("USER_EMAIL");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("GdprBase")
                        .HasColumnType("bit")
                        .HasColumnName("gdprBase");

                    b.Property<DateTime?>("GdprBaseDT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("gdprDate");

                    b.Property<ulong?>("GdprNews")
                        .HasColumnType("bit")
                        .HasColumnName("gdprNews");

                    b.Property<DateTime?>("GdprNewsDT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("gdprNewsDate");

                    b.Property<int>("InternalNumber")
                        .HasColumnType("int")
                        .HasColumnName("USER_NUMBER");

                    b.Property<string>("Jmeno")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_JMENO");

                    b.Property<int?>("LastLogin")
                        .HasColumnType("int")
                        .HasColumnName("USER_LAST_LOGIN");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MayCheaper")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_NAZEV");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_HESLO");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_TEL");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Platnost")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("USER_PLATNOST");

                    b.Property<string>("Posta")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_POSTA");

                    b.Property<string>("Poznamka")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_POPIS");

                    b.Property<string>("Poznamka2")
                        .HasColumnType("longtext")
                        .HasColumnName("Note2");

                    b.Property<string>("Prijmeni")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_PRIJMENI");

                    b.Property<string>("Psc")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_PSC");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Titul")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_TITUL");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ulice")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_ULICE");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("USER_NICK");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users_8", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Users.User8Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext")
                        .HasColumnName("nazev");

                    b.Property<int>("PobockaId")
                        .HasColumnType("int")
                        .HasColumnName("pobocka_id");

                    b.Property<string>("Popis")
                        .HasColumnType("longtext")
                        .HasColumnName("popis");

                    b.HasKey("Id");

                    b.ToTable("users_category", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Users.UserRoles8", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RU_ROLE_ID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("RU_USER_ID");

                    b.Property<int?>("RoleId1")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("role_for_user", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Videa.UserVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivovano")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AktivovanoDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<int>("Kredity")
                        .HasColumnType("int");

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<bool>("Zaplaceno")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ZaplacenoDt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Zobrazeno")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ZobrazenoDt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("users_videa", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Videa.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<int>("Kredity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("videa", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Zakaznik.User8GroupUser", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("GroupId", "UserId");

                    b.ToTable("users_category_binding", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("spin_roleclaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("spin_userclaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("spin_userlogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("spin_usertoken", (string)null);
                });

            modelBuilder.Entity("Diva2.Core.Main.Notifications.NotificationDelivery", b =>
                {
                    b.HasOne("Diva2.Core.Main.Notifications.UserDevice", "UserDevice")
                        .WithMany("Deliveries")
                        .HasForeignKey("UserDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diva2.Core.Main.Notifications.UserNotification", "UserNotification")
                        .WithMany("Deliveries")
                        .HasForeignKey("UserNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDevice");

                    b.Navigation("UserNotification");
                });

            modelBuilder.Entity("Diva2.Core.Main.Notifications.UserDevice", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diva2.Core.Main.Notifications.UserNotification", b =>
                {
                    b.HasOne("Diva2.Core.Main.Lessons.Lekce", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Diva2.Core.Main.Users.User8", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.LekceUser", b =>
                {
                    b.HasOne("Diva2.Core.Main.Lessons.Lekce", "Lekce")
                        .WithMany()
                        .HasForeignKey("LekceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diva2.Core.Main.Users.User8", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lekce");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserLekceChange", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserTransakce", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserZbytekKredit", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", null)
                        .WithMany("Kredity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diva2.Core.Main.Trans.UserZbytekKreditCas", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", null)
                        .WithMany("KredityCas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diva2.Core.Main.Users.UserRoles8", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.Role8", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diva2.Core.Main.Users.Role8", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId1");

                    b.HasOne("Diva2.Core.Main.Users.User8", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diva2.Core.Main.Users.User8", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diva2.Core.Main.Videa.UserVideo", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diva2.Core.Main.Videa.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.Role8", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Diva2.Core.Main.Users.User8", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diva2.Core.Main.Notifications.UserDevice", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("Diva2.Core.Main.Notifications.UserNotification", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("Diva2.Core.Main.Users.User8", b =>
                {
                    b.Navigation("Kredity");

                    b.Navigation("KredityCas");
                });
#pragma warning restore 612, 618
        }
    }
}
